version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: mariadb:10.4-bionic
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=soma_finances
            - MYSQL_USER=soma_finances
            - MYSQL_PASSWORD=CjkmgfdUhfvgs
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

