# Generated by Django 3.0.1 on 2019-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=260, verbose_name='тип')),
                ('min_price', models.IntegerField(verbose_name='мінімальна ціна')),
                ('max_price', models.IntegerField(verbose_name='максимальна ціна')),
            ],
        ),
    ]
