# Generated by Django 3.0.1 on 2019-12-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name="ім'я")),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name="ім'я")),
            ],
        ),
        migrations.RenameModel(
            old_name='Papers',
            new_name='Paper',
        ),
        migrations.CreateModel(
            name='RegularClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='назва')),
                ('start_date', models.DateField(verbose_name='дата початку')),
                ('end_date', models.DateField(verbose_name='дата кінця')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField()),
                ('price', models.IntegerField()),
                ('expired', models.BinaryField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Paper')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='papers',
            field=models.ManyToManyField(through='finances.ParticipantPaper', to='finances.Paper'),
        ),
        migrations.CreateModel(
            name='ClassUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('participants', models.ManyToManyField(through='finances.ClassParticipation', to='finances.Participant')),
                ('regular_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.RegularClass')),
            ],
        ),
        migrations.AddField(
            model_name='classparticipation',
            name='class_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.ClassUnit'),
        ),
        migrations.AddField(
            model_name='classparticipation',
            name='paper_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.ParticipantPaper'),
        ),
        migrations.AddField(
            model_name='classparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Participant'),
        ),
    ]
