# Generated by Django 3.0.1 on 2019-12-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20191219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата кінця'),
        ),
    ]
