# Generated by Django 3.0.1 on 2019-12-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20191220_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classunit',
            options={'ordering': ['-date', 'regular_class'], 'verbose_name': 'Конкретне заняття', 'verbose_name_plural': 'Конкретні заняття'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'Папірець', 'verbose_name_plural': 'Папірці'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Учасни_ця', 'verbose_name_plural': 'Учасни_ці'},
        ),
        migrations.AlterModelOptions(
            name='regularclass',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Викладач_ка', 'verbose_name_plural': 'Викладач_ки'},
        ),
        migrations.AddField(
            model_name='classparticipation',
            name='one_time_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='одноразова ціна'),
        ),
        migrations.AlterField(
            model_name='classparticipation',
            name='paper_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.ParticipantPaper'),
        ),
    ]
