# Generated by Django 3.0.1 on 2020-01-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20191230_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='classparticipation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='коментар'),
        ),
    ]
