# Generated by Django 3.0.1 on 2020-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20200104_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='one_time_price',
            field=models.FloatField(verbose_name='ціна за одне заняття'),
        ),
    ]
