# Generated by Django 3.0.1 on 2020-01-04 19:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20200104_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='classparticipation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='classparticipation',
            name='one_time_price',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='one_time_price',
        ),
        migrations.RemoveField(
            model_name='participantpaper',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='participantpaper',
            name='price',
        ),
        migrations.RemoveField(
            model_name='regularclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classparticipation',
            name='paid_one_time_price',
            field=models.BooleanField(default=True, verbose_name='одноразовий внесок'),
        ),
        migrations.AddField(
            model_name='classunit',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='коментар'),
        ),
        migrations.AddField(
            model_name='classunit',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.Teacher', verbose_name='викладач/ка'),
        ),
        migrations.AddField(
            model_name='paper',
            name='days_valid',
            field=models.IntegerField(default=30, verbose_name='скільки днів дійсний'),
        ),
        migrations.AddField(
            model_name='paper',
            name='number_of_uses',
            field=models.IntegerField(blank=True, null=True, verbose_name='скільки занять дійсний'),
        ),
        migrations.AddField(
            model_name='paper',
            name='price',
            field=models.IntegerField(default=0, verbose_name='внесок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='дата першого знаяття'),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='електронна адреса'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', verbose_name='номер телефону'),
        ),
        migrations.AddField(
            model_name='participantpaper',
            name='is_volunteer',
            field=models.BinaryField(default=False, verbose_name='чи волонтерський?'),
        ),
        migrations.AddField(
            model_name='regularclass',
            name='one_time_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='ціна за одне заняття'),
        ),
    ]
