# Generated by Django 3.0.1 on 2020-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20200104_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classparticipation',
            name='paid_one_time_price',
            field=models.BooleanField(default=False, verbose_name='одноразовий внесок'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=260, verbose_name='назва'),
        ),
    ]
