# Generated by Django 3.0.1 on 2020-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20200105_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpaper',
            name='is_volunteer',
            field=models.BooleanField(default=False, verbose_name='чи волонтерський?'),
        ),
    ]
