# Generated by Django 3.0.1 on 2020-01-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_auto_20200105_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('amount', models.IntegerField(verbose_name='сума')),
                ('source', models.TextField(blank=True, null=True, verbose_name='джерело')),
            ],
        ),
    ]
