# Generated by Django 3.0.1 on 2020-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='назва')),
                ('date', models.DateField(verbose_name='дата')),
                ('admission_sum', models.IntegerField(verbose_name='сума внесків за вхід')),
                ('bar_sum', models.IntegerField(verbose_name='сума за бар')),
            ],
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'Пожертва', 'verbose_name_plural': 'Пожертви'},
        ),
    ]
