# Generated by Django 3.0.1 on 2020-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_auto_20200113_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleevent',
            options={'ordering': ['-date'], 'verbose_name': 'Одноразова подія', 'verbose_name_plural': 'Одноразові події'},
        ),
        migrations.AlterField(
            model_name='singleevent',
            name='admission_sum',
            field=models.IntegerField(default=0, verbose_name='сума внесків'),
        ),
        migrations.AlterField(
            model_name='singleevent',
            name='bar_sum',
            field=models.IntegerField(default=0, verbose_name='сума за бар'),
        ),
    ]
