# Generated by Django 3.0.1 on 2020-01-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20200113_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('main', 'основні'), ('bar', 'бар'), ('sapce', 'простір'), ('fees', 'гонорари')], max_length=191, verbose_name='категорія')),
                ('description', models.CharField(max_length=250, verbose_name='опис')),
                ('date', models.DateField(verbose_name='дата')),
                ('amount', models.IntegerField(default=0, verbose_name='сума')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
