# Generated by Django 3.0.1 on 2020-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MIN_ONE_TIME_PAPER_PRICE', 'Вартість одного використання мегапапірця'), ('MIN_TEACHERS_SALARY', 'Мінімальна винагорода за заняття')], max_length=100, unique=True, verbose_name='назва')),
                ('value', models.FloatField(default=0, verbose_name='значення')),
                ('description', models.TextField(blank=True, verbose_name='додаткова інформація')),
            ],
            options={
                'verbose_name': 'Стале значення',
                'verbose_name_plural': 'Сталі значення',
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Витрати', 'verbose_name_plural': 'Витрати'},
        ),
    ]
