# Generated by Django 3.0.1 on 2020-02-05 13:35

from django.db import migrations


MIN_TEACHERS_SALARY_DESCRIPTION = """
Мінімальна винагорода, яку вчитель отримує за проведене заняття,
не залежно від того, скільки учасників були присутніми.
"""

MIN_ONE_TIME_PAPER_PRICE_DESCIRPTION = """
При обрахунку учительської винагороди за заняття за кожного учасника
з папірцем нараховується (ціна папірця/дозволена кількість використань папірця/2) грн.
Але мега папірець не має обмежень на кількість використань, тому для нього
замість такої формули використовуємо значення цієї змінної поділене на два.
"""


def fill_constants(apps, schema_editor):
    Constants = apps.get_model('finances', 'Constants')
    db_alias = schema_editor.connection.alias
    Constants.objects.using(db_alias).bulk_create([
        Constants(
            name='MIN_ONE_TIME_PAPER_PRICE', value=70,
            description=MIN_ONE_TIME_PAPER_PRICE_DESCIRPTION,
        ),
        Constants(
            name='MIN_TEACHERS_SALARY', value=100,
            description=MIN_TEACHERS_SALARY_DESCRIPTION
        )
    ])


def reverse_fill_constants(apps, schema_editor):
    Constants = apps.get_model('finances', 'Constants')
    db_alias = schema_editor.connection.alias
    Constants.objects.using(db_alias).filter(
        name='MIN_ONE_TIME_PAPER_PRICE').delete()
    Constants.objects.using(db_alias).filter(
        name='MIN_TEACHERS_SALARY').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_auto_20200205_1512'),
    ]

    operations = [
        migrations.RunPython(fill_constants, reverse_fill_constants),
    ]
