# Generated by Django 3.0.1 on 2020-02-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_auto_20200205_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='листа надіслано'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='дата реєстрації'),
        ),
    ]
