# Generated by Django 3.0.3 on 2020-02-21 11:59

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_auto_20200205_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('main', 'основні'), ('bar', 'бар'), ('space', 'простір'), ('fees', 'гонорари')], max_length=191, verbose_name='категорія'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='participantpaper',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата купівлі'),
        ),
        migrations.AlterField(
            model_name='participantpaper',
            name='date_purchased',
            field=models.DateField(auto_now=True, verbose_name='дата купівлі'),
        ),
        migrations.AddConstraint(
            model_name='classparticipation',
            constraint=models.UniqueConstraint(fields=('class_unit', 'participant'), name='finances_classparticipation_unit_and_participant_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='classparticipation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('paper_used__isnull', False), ('paid_one_time_price', False)), models.Q(('paper_used__isnull', True), ('paid_one_time_price', True)), _connector='OR'), name='finances_classparticipation_only_one_payment_method'),
        ),
    ]
