# Generated by Django 3.0.3 on 2020-03-12 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_paper_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='participantpaper',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата купівлі'),
        ),
    ]
